"""
    Tagesordnungen API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""

import unittest

from deutschland.bundestag_tagesordnung.api.default_api import DefaultApi  # noqa: E501

from deutschland import bundestag_tagesordnung


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_bt_to_csv_get(self):
        """Test case for bt_to_csv_get

        Tagesordnungen im CSV-Format abrufen  # noqa: E501
        """
        pass

    def test_bt_to_ical_get(self):
        """Test case for bt_to_ical_get

        Tagesordnungen im iCal-Format abrufen  # noqa: E501
        """
        pass

    def test_bt_to_json_get(self):
        """Test case for bt_to_json_get

        Tagesordnungen im JSON-Format abrufen  # noqa: E501
        """
        pass

    def test_bt_to_xml_get(self):
        """Test case for bt_to_xml_get

        Tagesordnungen im XML-Format abrufen  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
